### ISSUE TITLE
Validate VPA: expand the request/response by default on page open

### ISSUE THREAD

**Issue by pranitbauva1997** [SetuHQ/docs#12]
@aditya-67 When I open https://staging.docs.setu.co/data/bav/validate-vpa/quickstart, I see the section for Validate VPA with tabs as `200`, `400`, and `500`. By default on page open, the request and response is collapsed as shown in the screenshot attached. What changes are required to "fully open" the request/response body on page load?

![screenshot-2022-12-22-14:41:37](https://user-images.githubusercontent.com/2959938/209100350-86b269fa-cc45-447e-95d6-e797e3a28787.png)

cc: @ritwickdey

**Comment by aditya-67** [comment]
@pranitbauva1997 
The reason for having the accordion closed by default is to provide a view of all the available responses for the status code in one go. If it is open by default, the below response may be missed due to the content length and will be out of view.

I would like to understand why would you want it to be open by default, so I can see if there is any other way to solve

**Comment by pranitbauva1997** [comment]
@aditya-67 When I first visited the site I couldn't immediately find where the request/responses are displayed that I knew it was in the earlier PR. It took me a while to find out I have to click on the faint downward facing arrow to see the request and response body.

If we keep the request response body open, one can still see the different types of response codes.

**Comment by aditya-67** [comment]
@pranitbauva1997 Understood. I made those changes for this page. Please refer [here](https://github.com/SetuHQ/docs/blob/staging/content/data/bav/validate-vpa/quickstart.mdx?plain=1#L42) on how you can do this in the future.

You can also refer to the updated sample page, [click here](https://github.com/SetuHQ/docs/blob/staging/content/sample-category/sample-product/sample-page.mdx?plain=1#L144)

Please verify and let me know, we can close this.

**Comment by pranitbauva1997** [comment]
@aditya-67 This works, thanks for working on this.
