### ISSUE TITLE
Unable to create a new template for eSign by Aadhar

### ISSUE THREAD

**Issue by sanjeebsarkar** [SetuHQ/docs#201]
Hi, 
Thank you so much for sharing these API docs , and a detailed description on its functionalities. Unfortunately I have hit a snag, I am trying to create a custom template for eSign using Aadhar, and I am using this api to create custom template : 

url : https://dg-sandbox.setu.co/api/templates

request cUrl : 

``
curl --location 'https://dg-sandbox.setu.co/api/templates' \
--header 'x-client-id: <-removed-on-purpose>' \
--header 'x-client-secret: <-removed-on-purpose>' \
--header 'x-product-instance-id: <-removed-on-purpose>' \
--header 'Accept: application/json' \
--form 'template="\"myTemplate\""' \
--form 'parameters="{\"name\":[100,590],\"fundraiser\":[100,565],\"beneficiaryName\":[210,540],\"beneficiaryRelationship\":[250,515],\"date\":[90,487],\"amount\":[350,487],\"account\":[410,462],\"accountHolderRelationship\":[270,437]}"'
``
and I am getting this error : 
``
{
    "error": {
        "code": "invalid_payload",
        "detail": "Missing required parameter in an uploaded file: template",
        "traceId": "1-670ba213-5aed94337e2e34fe64104f2c"
    }
}
``
Please assist me with this issue, also if I am in the wrong repository to raise this kind of issue, please redirect me to the right place, I will raise it there. 

Thank you .

**Comment by sanjeebsarkar** [comment]
Hi,
Thank you so much for your reply, and please excuse my delay in giving you a response. I will try this out, and see the result. I have another question, what would be the content of the .pdf ? is it the custom signature drawing ?

**Comment by oreanroy** [comment]
The .pdf is any PDF file for which you want to create a template.

If you are a business or an individual trying to explore our Adhaar Esing API for a use case.

Please write to us at support@setu.co

**Comment by sanjeebsarkar** [comment]
Hi ,
Thank you for your reply, please give me some time, I will test this out in sometime.

**Comment by sanjeebsarkar** [comment]
Hi ,
I just tried the solution you provided, and I am getting this below error : 

{
    "code": "invalid_template_config",
    "detail": "Invalid template config format",
    "traceId": "1-6710bb62-7e1f381b6944cc3c71268b44"
} 

so its a little improvement from the previous error. 

Unfortunately, I tried to use the request payload mentioned in the documentation in this link : 

https://docs.setu.co/data/esign/api-reference#/category~eSign_Template/operation~UploadeSigndocumenttemplate 

and this was the request payload is HTTP format : 

curl --location 'https://dg-sandbox.setu.co/api/templates' \
--header 'x-client-id: <client-id>' \
--header 'x-client-secret:  <client-secret>  ' \
--header 'x-product-instance-id:  <x-product-instance-id >  ' \
--header 'Content-Type: multipart/form-data' \
--header 'Accept: application/json' \
--form 'template=@"/K:/setuTest/setu_esign_document.pdf"' \
--form 'parameters="\"{\\\"name\\\":[100,590],\\\"fundraiser\\\":[100,565],\\\"beneficiaryName\\\":[210,540],\\\"beneficiaryRelationship\\\":[250,515],\\\"date\\\":[90,487],\\\"amount\\\":[350,487],\\\"account\\\":[410,462],\\\"accountHolderRelationship\\\":[270,437]}\""' 

and this is the response I am getting : 

{
    "code": "invalid_template_config",
    "detail": "Invalid template config format",
    "traceId": "1-6710bb62-7e1f381b6944cc3c71268b44"
}

If you can please comment on my mistake here, it will be helpful , also, I will send the a mail to that support mail id which you have shared earlier.

**Comment by aditya-67** [comment]
Hey @sanjeebsarkar, please contact [Setu Support](https://setu.co/support/) with the above issue. Our team will be on your case and resolve it right away. 

Closing this issue

**Comment by sanjeebsarkar** [comment]
Hi,
Yes, I will do that. Thank you for your support.
